### ISSUE TITLE
bioinformatics-algorithms/statistical_representation_of_motifs/missingMotif.py countKmers(self, seq)

### ISSUE THREAD

**Issue by junjieahaha** [edevog/bioinformatics-algorithms#1]
for k in range(self.kmerMin, self.kmerMax + 1):
            for i in range(len(seq) - self.kmerMax + 1):
                kmerFromSeq = (seq[i:i+k])

I ran this function: example  "AATCGGG" kmerMin=4 kmerMax=6
it outputs
AATC
ATCG
AATCG
ATCGG
AATCGG
ATCGGG

should it be 
for k in range(self.kmerMin, self.kmerMax + 1):
            for i in range(len(seq) - k + 1):
                kmerFromSeq = (seq[i:i+k])

it outputs:
AATC
ATCG
TCGG
CGGG
AATCG
ATCGG
ATCGGG
ATCGGG
I am curious if this is a special usage or a bug? :)

**Comment by edevog** [comment]
Hello,

This is a bug in the code. I found previous iterations of my program had
the correct range for 'i'. Thank you for pointing this out, I will correct
it.

Best regards,
Beth
